[project]
name = "fastapi-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "takao827", email = "takao827.dds@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.fastapi]
entrypoint = "app.main:app"